export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  CATALOG_READ: 'catalog:read',
  CATALOG_WRITE: 'catalog:write',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  ORDER_READ: 'order:read',
  ORDER_UPDATE: 'order:update',
  COUPON_MANAGE: 'coupon:manage',
  REVIEW_MODERATE: 'review:moderate',
  REPORT_READ: 'report:read',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LIST = Object.values(PERMISSIONS) as [Permission, ...Permission[]];

export const STOCK_MOVEMENT_TYPES = {
  RESTOCK: 'RESTOCK',
  ADJUSTMENT: 'ADJUSTMENT',
  RESERVE: 'RESERVE',
  COMMIT: 'COMMIT',
  RELEASE: 'RELEASE',
} as const;

export type StockMovementType = (typeof STOCK_MOVEMENT_TYPES)[keyof typeof STOCK_MOVEMENT_TYPES];

export const AUDIT_ACTIONS = {
  STAFF_CREATED: 'STAFF_CREATED',
  STAFF_STATUS_UPDATED: 'STAFF_STATUS_UPDATED',
  STAFF_PERMISSIONS_UPDATED: 'STAFF_PERMISSIONS_UPDATED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  BRAND_CREATED: 'BRAND_CREATED',
  BRAND_UPDATED: 'BRAND_UPDATED',
  BRAND_DELETED: 'BRAND_DELETED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  VARIANT_CREATED: 'VARIANT_CREATED',
  VARIANT_UPDATED: 'VARIANT_UPDATED',
  VARIANT_DELETED: 'VARIANT_DELETED',
  INVENTORY_RESTOCKED: 'INVENTORY_RESTOCKED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INACTIVE_ACCOUNT: 'INACTIVE_ACCOUNT',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  INVALID_TARGET_ROLE: 'INVALID_TARGET_ROLE',
  CANNOT_DEACTIVATE_LAST_ADMIN: 'CANNOT_DEACTIVATE_LAST_ADMIN',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_EXISTS: 'CATEGORY_SLUG_EXISTS',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CATEGORY_CYCLIC_HIERARCHY: 'CATEGORY_CYCLIC_HIERARCHY',
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BRAND_SLUG_EXISTS: 'BRAND_SLUG_EXISTS',
  BRAND_HAS_PRODUCTS: 'BRAND_HAS_PRODUCTS',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_EXISTS: 'PRODUCT_SLUG_EXISTS',
  PRODUCT_SKU_EXISTS: 'PRODUCT_SKU_EXISTS',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  PRODUCT_IMAGE_NOT_FOUND: 'PRODUCT_IMAGE_NOT_FOUND',
  SPECIFICATION_NOT_FOUND: 'SPECIFICATION_NOT_FOUND',
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_STOCK_ADJUSTMENT: 'INVALID_STOCK_ADJUSTMENT',
  INVALID_STOCK_OPERATION: 'INVALID_STOCK_OPERATION',
  STOCK_EVENT_CONFLICT: 'STOCK_EVENT_CONFLICT',
  STOCK_HISTORY_EXISTS: 'STOCK_HISTORY_EXISTS',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_REQUIRED: 'FILE_REQUIRED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const UPLOAD_PURPOSES = {
  PRODUCT_IMAGE: 'PRODUCT_IMAGE',
  BRAND_LOGO: 'BRAND_LOGO',
  USER_AVATAR: 'USER_AVATAR',
} as const;

export type UploadPurpose = (typeof UPLOAD_PURPOSES)[keyof typeof UPLOAD_PURPOSES];

export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: '30d',
  REFRESH_TOKEN_EXPIRES_IN: '30d',
  REFRESH_TOKEN_EXPIRES_IN_DAYS: 30,
  BCRYPT_SALT_ROUNDS: 12,
} as const;

export const PHONE_REGEX = /^(0|\+84)[35789][0-9]{8}$/;
