export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  STAFF: 'STAFF',
  ADMIN: 'ADMIN',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  CATALOG_READ: 'catalog:read',
  CATALOG_WRITE: 'catalog:write',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  ORDER_READ: 'order:read',
  ORDER_UPDATE: 'order:update',
  COUPON_MANAGE: 'coupon:manage',
  REVIEW_MODERATE: 'review:moderate',
  REPORT_READ: 'report:read',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const PERMISSION_LIST = Object.values(PERMISSIONS) as [Permission, ...Permission[]];

export const STOCK_MOVEMENT_TYPES = {
  RESTOCK: 'RESTOCK',
  ADJUSTMENT: 'ADJUSTMENT',
  RESERVE: 'RESERVE',
  COMMIT: 'COMMIT',
  RELEASE: 'RELEASE',
} as const;

export type StockMovementType = (typeof STOCK_MOVEMENT_TYPES)[keyof typeof STOCK_MOVEMENT_TYPES];

export const DISCOUNT_TYPES = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED_AMOUNT: 'FIXED_AMOUNT',
} as const;

export type DiscountType = (typeof DISCOUNT_TYPES)[keyof typeof DISCOUNT_TYPES];

export const ORDER_STATUSES = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  SHIPPING: 'SHIPPING',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',
} as const;

export type OrderStatus = (typeof ORDER_STATUSES)[keyof typeof ORDER_STATUSES];

export const PAYMENT_METHODS = {
  COD: 'COD',
  VNPAY: 'VNPAY',
} as const;

export type PaymentMethod = (typeof PAYMENT_METHODS)[keyof typeof PAYMENT_METHODS];

export const PAYMENT_STATUSES = {
  PENDING: 'PENDING',
  PAID: 'PAID',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
} as const;

export type PaymentStatus = (typeof PAYMENT_STATUSES)[keyof typeof PAYMENT_STATUSES];

export const PAYMENT_TRANSACTION_STATUSES = {
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  EXPIRED: 'EXPIRED',
} as const;

export type PaymentTransactionStatus =
  (typeof PAYMENT_TRANSACTION_STATUSES)[keyof typeof PAYMENT_TRANSACTION_STATUSES];

export const AUDIT_ACTIONS = {
  STAFF_CREATED: 'STAFF_CREATED',
  STAFF_STATUS_UPDATED: 'STAFF_STATUS_UPDATED',
  STAFF_PERMISSIONS_UPDATED: 'STAFF_PERMISSIONS_UPDATED',
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  BRAND_CREATED: 'BRAND_CREATED',
  BRAND_UPDATED: 'BRAND_UPDATED',
  BRAND_DELETED: 'BRAND_DELETED',
  PRODUCT_CREATED: 'PRODUCT_CREATED',
  PRODUCT_UPDATED: 'PRODUCT_UPDATED',
  PRODUCT_DELETED: 'PRODUCT_DELETED',
  VARIANT_CREATED: 'VARIANT_CREATED',
  VARIANT_UPDATED: 'VARIANT_UPDATED',
  VARIANT_DELETED: 'VARIANT_DELETED',
  INVENTORY_RESTOCKED: 'INVENTORY_RESTOCKED',
  INVENTORY_ADJUSTED: 'INVENTORY_ADJUSTED',
  COUPON_CREATED: 'COUPON_CREATED',
  COUPON_UPDATED: 'COUPON_UPDATED',
  COUPON_DELETED: 'COUPON_DELETED',
  ORDER_CREATED: 'ORDER_CREATED',
  ORDER_STATUS_UPDATED: 'ORDER_STATUS_UPDATED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',
  PAYMENT_URL_CREATED: 'PAYMENT_URL_CREATED',
  PAYMENT_IPN_PROCESSED: 'PAYMENT_IPN_PROCESSED',
  PAYMENT_IPN_FAILED: 'PAYMENT_IPN_FAILED',
  PAYMENT_IPN_POST_TERMINATION_RECONCILIATION: 'PAYMENT_IPN_POST_TERMINATION_RECONCILIATION',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INACTIVE_ACCOUNT: 'INACTIVE_ACCOUNT',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  TOKEN_REUSE_DETECTED: 'TOKEN_REUSE_DETECTED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  STAFF_NOT_FOUND: 'STAFF_NOT_FOUND',
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  INVALID_TARGET_ROLE: 'INVALID_TARGET_ROLE',
  CANNOT_DEACTIVATE_LAST_ADMIN: 'CANNOT_DEACTIVATE_LAST_ADMIN',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_EXISTS: 'CATEGORY_SLUG_EXISTS',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',
  CATEGORY_CYCLIC_HIERARCHY: 'CATEGORY_CYCLIC_HIERARCHY',
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',
  BRAND_SLUG_EXISTS: 'BRAND_SLUG_EXISTS',
  BRAND_HAS_PRODUCTS: 'BRAND_HAS_PRODUCTS',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_EXISTS: 'PRODUCT_SLUG_EXISTS',
  PRODUCT_SKU_EXISTS: 'PRODUCT_SKU_EXISTS',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  VARIANT_INACTIVE: 'VARIANT_INACTIVE',
  PRODUCT_IMAGE_NOT_FOUND: 'PRODUCT_IMAGE_NOT_FOUND',
  SPECIFICATION_NOT_FOUND: 'SPECIFICATION_NOT_FOUND',
  INVENTORY_NOT_FOUND: 'INVENTORY_NOT_FOUND',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  INVALID_STOCK_ADJUSTMENT: 'INVALID_STOCK_ADJUSTMENT',
  INVALID_STOCK_OPERATION: 'INVALID_STOCK_OPERATION',
  STOCK_EVENT_CONFLICT: 'STOCK_EVENT_CONFLICT',
  STOCK_HISTORY_EXISTS: 'STOCK_HISTORY_EXISTS',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_SIZE_EXCEEDED: 'FILE_SIZE_EXCEEDED',
  FILE_REQUIRED: 'FILE_REQUIRED',
  CART_NOT_FOUND: 'CART_NOT_FOUND',
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_ITEM_QUANTITY_INVALID: 'CART_ITEM_QUANTITY_INVALID',
  CART_NO_AVAILABLE_ITEMS: 'CART_NO_AVAILABLE_ITEMS',
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_CODE_EXISTS: 'COUPON_CODE_EXISTS',
  COUPON_INACTIVE: 'COUPON_INACTIVE',
  COUPON_NOT_STARTED: 'COUPON_NOT_STARTED',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_MIN_ORDER_NOT_MET: 'COUPON_MIN_ORDER_NOT_MET',
  COUPON_USAGE_LIMIT_EXCEEDED: 'COUPON_USAGE_LIMIT_EXCEEDED',
  COUPON_USER_LIMIT_EXCEEDED: 'COUPON_USER_LIMIT_EXCEEDED',
  COUPON_CANNOT_DELETE_USED: 'COUPON_CANNOT_DELETE_USED',
  INVALID_COUPON_DATES: 'INVALID_COUPON_DATES',
  INVALID_COUPON_LIMITS: 'INVALID_COUPON_LIMITS',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_ITEMS_EMPTY: 'ORDER_ITEMS_EMPTY',
  ORDER_CANNOT_CANCEL: 'ORDER_CANNOT_CANCEL',
  ORDER_PAID_CANNOT_CANCEL: 'ORDER_PAID_CANNOT_CANCEL',
  ORDER_INVALID_STATE_TRANSITION: 'ORDER_INVALID_STATE_TRANSITION',
  ORDER_VNPAY_ADMIN_CONFIRM_NOT_ALLOWED: 'ORDER_VNPAY_ADMIN_CONFIRM_NOT_ALLOWED',
  ORDER_CART_EMPTY: 'ORDER_CART_EMPTY',
  ORDER_CART_ITEMS_UNAVAILABLE: 'ORDER_CART_ITEMS_UNAVAILABLE',
  ORDER_ADDRESS_REQUIRED: 'ORDER_ADDRESS_REQUIRED',
  ORDER_VARIANT_ORDERED_CANNOT_DELETE: 'ORDER_VARIANT_ORDERED_CANNOT_DELETE',
  PAYMENT_ORDER_NOT_PAYABLE: 'PAYMENT_ORDER_NOT_PAYABLE',
  PAYMENT_CHECKSUM_INVALID: 'PAYMENT_CHECKSUM_INVALID',
  PAYMENT_TRANSACTION_NOT_FOUND: 'PAYMENT_TRANSACTION_NOT_FOUND',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const UPLOAD_PURPOSES = {
  PRODUCT_IMAGE: 'PRODUCT_IMAGE',
  BRAND_LOGO: 'BRAND_LOGO',
  USER_AVATAR: 'USER_AVATAR',
} as const;

export type UploadPurpose = (typeof UPLOAD_PURPOSES)[keyof typeof UPLOAD_PURPOSES];

export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: '30d',
  REFRESH_TOKEN_EXPIRES_IN: '30d',
  REFRESH_TOKEN_EXPIRES_IN_DAYS: 30,
  BCRYPT_SALT_ROUNDS: 12,
} as const;

export const PHONE_REGEX = /^(0|\+84)[35789][0-9]{8}$/;
